### PR TITLE
Added fix for segment duration calculations with TRUN samples involvi…

### PR DESCRIPTION
**Pull request by MathumathiSundaram**
Added fix for segment duration calculations with TRUN samples involving TRUN and TFHD flags

### CODE REVIEW

**Comment by kevinGodell** [comment]
HI. Thanks for the pull request. Can you please make it against the "duration" branch? Also, can you please provide a video sample or ffmpeg params to generate a video that was not having its duration read correctly?

**Comment by MathumathiSundaram** [comment]
Hi Kevin,

The forked repository does not list duration branch.

[image: image.png]

Thanks and regards,
Mathumathi.

**Comment by kevinGodell** [comment]
i think you would have to run, `git fetch`, then `git checkout duration`

**Comment by kevinGodell** [comment]
code was moved to other pull request https://github.com/kevinGodell/mp4frag/pull/23

**Pull request closed without merging**
